# Generated by Django 3.1.4 on 2020-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_author_username', models.CharField(max_length=35)),
                ('msg_content', models.TextField()),
                ('msg_send_time', models.DateTimeField(verbose_name='sended')),
            ],
        ),
    ]
