# Generated by Django 3.1.4 on 2020-12-20 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 19, 1, 0, 251009), verbose_name='sended'),
        ),
    ]
