# Generated by Django 3.1.4 on 2020-12-23 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201220_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 19, 13, 30, 307030), verbose_name='sended'),
        ),
    ]
