# Generated by Django 3.1.4 on 2021-01-13 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201223_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg_send_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 21, 0, 3, 399080), verbose_name='sended'),
        ),
    ]
